baseURL = "https://hugo-blog0.netlify.app/"
languageCode = "en-us"
title = "Hugo-blog"


# Navbar Menus
[[menu.main]]
name    = "Blog"
url     = "blog"


[Author]
  name = "Gurusabarish"
  website = "https://github.com/gurusabarish"