baseURL: "https://hugo-profile.netlify.app/"
languageCode: "en-us"
title: "Hugo-profile"

Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: "/images/hugo.png"
  description: "Portfolio and personal blog of gurusabarish"
  googleanalytics: ""
  disqus: ""
  contact: "false"

  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "blog"
    
  # Home
  name: "Gurusabarish"
  profile: "/images/avatar-370-456322.webp"
  github: "https://github.com/gurusabarish"
  linkedin: "https://linkedin.com/in/gurusabarish"
  twitter: "https://twitter.com/gurusabarishh"
  instagram: "https://instagram.com/gurusabarishh"

  # Do things { Please change the svg icons width="3em" height="3em" }
  thing1: "Python"
  thing2: "Machine learning"
  thing3: "Things for web"
  thing1_des: "I build something beautiful using Python."
  thing2_des: "I train robust models for various tasks."
  thing3_des: "I love to build things for web."

  # About
  profile_image: "/images/gurusabarish.jpg"
  jop: "Web developer"
  jops_about: "web developer and ML engineer"
  resume: ""
  
  projects:
  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"
  
  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "https://images.unsplash.com/photo-1532781914607-2031eca2f00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=7c625ea379640da3ef2e24f20df7ce8d"
    description:  "This is your description"
    url: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"
  

Author:
  name: "Gurusabarish"
  website: "https://github.com/gurusabarish"